mainprefix: "YourPrefix"
defaultjoinmessage: "**{user} Joined Invited By {Inviter} (Invites: {inv})**"
defaultleavemessage: "**{user} Left, Invited by {inviter}**"
token: "YourToken"
color: "BLUE"
